shipwright-io/cli

.gitignore, go.mod, go.sum, pkg/shp/cmd/root.go, pkg/shp/cmd/root_test.go, pkg/shp/suggestion/suggest.go, pkg/shp/suggestion/suggest_test.go, test/stub/cobra.go, vendor/github.com/texttheater/golang-levenshtein/levenshtein/LICENSE, vendor/github.com/texttheater/golang-levenshtein/levenshtein/go.mod, vendor/github.com/texttheater/golang-levenshtein/levenshtein/levenshtein.go, vendor/modules.txt
Earlier there were no suggestions for shp subcommands but with this patch entering wrong subcommands will give suggestions.
example:- 
```
$ shp build cr
Error: unknown command "cr" for "shp build"
Did you mean this?
create
```
Also updated the `.gitignore` file to ignore the binary generated after running `go build ./cmd/shp` and also ignoring `.vscode` dir
Signed-off-by: vinamra28 <vinjain@redhat.com>
=> Command Suggestion for Incorrect Subcommands

.github/pull_request_template.md
/assign @adambkaplan 
/assign @imjasonh 
for now this points to the contributing guide in the build repo, as I saw no contributing guide here
my preference would be that if we need a separate guide, it be done in a separate pr
=> add pr template in preparation for enabling release notes

pkg/shp/flags/build.go, pkg/shp/flags/build_test.go, pkg/shp/flags/buildrun.go, pkg/shp/flags/buildrun_test.go, pkg/shp/flags/doc.go, pkg/shp/flags/flags.go, pkg/shp/flags/strategy_kind_value.go, pkg/shp/flags/strategy_kind_value_test.go, pkg/shp/flags/string_pointer_value_test.go
Refactoring the flags using string-to-pointer inside a nested structure to avoid `StringPointerValue`. Additionally, covering the `flags` package with unit-tests, every command-line flag is checked.
Fixes #26 
Execute the following commands in order, so a new `BuildRun` object is created using a service-account named "test":
```bash
shp build create nodejs-ex --source-url="https://github.com/otaviof/nodejs-ex.git" # ...
shp buildrun create br --buildref-name=nodejs-ex --sa-name=test
oc get buildruns.shipwright.io br -o json |jq '.spec.serviceAccount'
```
The last command should confirm the desired service-account is in place:
```sh
$ oc get buildruns.shipwright.io br -o json |jq '.spec.serviceAccount'
{
"name": "test"
}
```
```release-note
- Fixing command-line flags based on …
```
=> Fixing Pointer-to-String Flags and Improve Testing

pkg/shp/cmd/build/doc.go, pkg/shp/cmd/buildrun/buildrun.go, pkg/shp/cmd/buildrun/doc.go, pkg/shp/flags/doc.go, pkg/shp/flags/flags.go, pkg/shp/params/params.go, pkg/shp/reactor/pod_watcher.go, pkg/shp/resource/doc.go, pkg/shp/resource/resource.go, pkg/shp/util/crud.go, pkg/shp/util/doc.go
General fixes for go-report-card, typos and minor refactoring. Fixing the following alerts:
```
$ goreportcard-cli -v
2021/07/03 09:25:37 disabling misspell on large repo...
Grade: A+ (99.9%)
Files: 2043
Issues: 10
gofmt: 100%
go_vet: 100%
gocyclo: 99%
pkg/shp/reactor/pod_watcher.go
Line 59: warning: cyclomatic complexity 18 of function (*PodWatcher).Start() is high (> 15) (gocyclo)
golint: 99%
pkg/shp/params/params.go
Line 11: warning: comment on exported type Params should be of the form "Params ..." (with optional leading article) (golint)
Line 53: warning: exported method Params.ClientSet should have comment or be unexported (golint)
pkg/shp/flags/flags.go
Line 13: warning: exported const BuildrefNameFlag should have comment (or a comment on this block) or be unexported (golint) …
```
=> Go-Report-Card Fixes

hack/install-kubectl.sh
Kubectl binary download script modification has been done to accommodate support for all Linux distributions. It is relatively short, requires no sudo and should run on most distros just fine.
```release-note
NONE
```
=> Add generic Kubectl binary download script for all Linux distributions

pkg/shp/cmd/build/run.go, pkg/shp/cmd/build/run_test.go
add unit test for previously provided live log follow / tail of invoking build run from referenced build via cli
unit tests uncovered some race conditions previously unseen with manual testing
/kind cleanup
/assign @otaviof 
/assign @coreydaley 
/assign @HeavyWombat 
after a bunch of back and forth with myself today (preceded by a conversation with @otaviof ) 
I gave up trying to get k8s fake clients to work with watches, etc. and am just testing the function in this package
we have tests in pod_watcher and tail for those functions
in looking at the panic we saw in @HeavyWombat 's https://github.com/shipwright-io/cli/pull/35 I do believe line 64 in run.go is in the Run() method, so in theory this test calling that method would have caught that error.
But as @otaviof mentioned to me today, …
=> Start buildrun follow logs test

.github/workflows/e2e.yaml, .github/workflows/unit.yaml, Makefile, README.md, docs/testing.md, hack/install-shipwright.sh, hack/install-tekton.sh, hack/verify-kind.sh, test/e2e/e2e.bats, test/e2e/helpers.sh
This pull-request introduces the machinery to run end-to-end tests, as described on the [enhancement-proposal](https://github.com/shipwright-io/build/blob/main/docs/proposals/cli.md#testing). That means, the following components are ready to use:
- `make verify-kind`: assure KinD's node is ready
- `make install-shipwright`: deploys Tekton and Shipwright Build Controller using the versions specified on the Makefile
- `make test-e2e`: runs the end-to-end tests under `./test/e2e` directory
GitHub Actions have been updated to run [BATs](https://github.com/bats-core/bats-core) e2e tests, in other works, to `make test-e2e` on each pull-request.
```release-note
NONE
```
=> Bootstrapping End-to-End Tests

pkg/shp/cmd/build/run_test.go
github actions back e2e runs turned up this panic in the new unit test I added in one of its recent runs:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b9e0d9]
goroutine 21 [running]:
testing.tRunner.func1.2({0x1c9bdc0, 0x2c0bd70})
/opt/hostedtoolcache/go/1.17.1/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.17.1/x64/src/testing/testing.go:1212 +0x3b6
panic({0x1c9bdc0, 0x2c0bd70})
/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/panic.go:1047 +0x266
github.com/shipwright-io/cli/pkg/shp/cmd/build.(*RunCommand).onEvent(0xc000379e30, 0xc0000ec800)
/home/runner/work/cli-1/cli-1/pkg/shp/cmd/build/run.go:121 +0xbd9
github.com/shipwright-io/cli/pkg/shp/cmd/build.TestStartBuildRunFollowLog(0xc0003644e0) …
```
=> more multi thread coordination need to avoid panics in TestStartBuildRunFollowLog

pkg/shp/cmd/build/create.go, pkg/shp/cmd/buildrun/create.go, test/e2e/e2e.bats, test/e2e/helpers.sh
Fixes #42 
`shp build create` and `shp buildrun create` now correctly handle their respective type creation by accepting and passing the build/buildrun to the shipwrigt client.
```release-note
`shp build create` and `shp buildrun create` now correctly handle their respective type creation by accepting and passing the build/buildrun to the shipwrigt client.
```
=> Pass name to shp for create build and create buildrun

pkg/shp/cmd/build/run_test.go
Fixes #48 
/kind bug
/assign @coreydaley 
/assign @jkhelil
- [ /] Includes tests if functionality changed/was added
- [ n/a] Includes docs if changes are user-facing
```release-note
NONE
```
=> more RunCommand initialization verification for TestStartBuildRunFollowLogs

pkg/shp/cmd/build/create.go, pkg/shp/cmd/build/delete.go, pkg/shp/cmd/build/list.go, pkg/shp/cmd/build/run.go, pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/cancel.go, pkg/shp/cmd/buildrun/create.go, pkg/shp/cmd/buildrun/delete.go, pkg/shp/cmd/buildrun/list.go, pkg/shp/cmd/buildrun/logs.go, pkg/shp/cmd/runner/interface.go, pkg/shp/cmd/runner/runner.go, pkg/shp/cmd/runner/runner_test.go, pkg/shp/params/params.go, pkg/shp/reactor/pod_watcher.go, pkg/shp/reactor/pod_watcher_test.go, test/e2e/run-follow.bats
Fixes #53
- adds/tweaks integration from k8s `--request-timeout` and `--context` options that `shp` inherits from k8s to apply request or context deadline timeout / aborts on `ship build run --follow`
- add callbacks for lack of pod events, including cross reference with build run when those occur, just as we do when pod events do occur (still no explicit buildrun watch to go with pod watch, as multiple watches proves untenable with unit testing, plus over-indulgent, as we only need buildrun for terminal states), to exit --follow
- slight refactor of SubCommand interface to allow for more initialization in Complete() vs. Run() for --follow
- which allowed vast simplification of data race prevention on RunCommand
- and removal of what proved to be kludgy thread coordination in --follow …
=> various run build -F/--follow fixes around timeout, lack of pods, and data races

pkg/shp/cmd/build/create.go, pkg/shp/cmd/buildrun/create.go, pkg/shp/flags/flags.go, pkg/shp/reactor/pod_watcher.go, pkg/shp/reactor/pod_watcher_test.go, pkg/shp/util/env.go, pkg/shp/util/env_test.go
If we pass an env which is not a valid key-value pair, cli breaks.
this handles that parsing of passed string and returns an error
if passed env is not in key=value pattern.
Ref https://github.com/shipwright-io/cli/pull/68#discussion_r739153809
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
```release-note
Fixes create cmd to return an error if env passed is not a valid key value pair
```
=> Fixes create cmds to return an error if env passed is invalid

pkg/shp/flags/build.go, pkg/shp/flags/build_test.go, pkg/shp/flags/flags.go, pkg/shp/flags/map_value.go, pkg/shp/flags/map_value_test.go, test/e2e/output-image-labels-annotations.bats
This adds support to specify labels and annotation for
output image.
There are 2 flags added for the `build create` command
- output-image-label
- output-image-annotation
Part of #66 
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
```release-note
Adds support to specify on Build objects labels and annotations to be set on output images
```
=>  Adds support for img labels and anno. in build create cmd 

cmd/shp/main.go, go.mod, test/e2e/e2e.bats, vendor/modules.txt
Just initialize [klog](https://github.com/kubernetes/klog) with go flags and add these flags to pflag as well.
Fixes #7
With this change its possible to enable k8s api communication, for example:
```bash
go run cmd/shp/main.go -v=10 br list
I1029 19:15:17.183378  141455 loader.go:379] Config loaded from file: ...kubeconfig
I1029 19:15:17.184151  141455 round_trippers.go:425] curl -k -v -XGET  -H "Authorization: Bearer <masked>" -H "Accept: application/json, */*" -H "User-Agent: main/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://api.crc.testing:6443/apis/shipwright.io/v1alpha1/namespaces/default/buildruns'
I1029 19:15:17.195693  141455 round_trippers.go:445] GET https://api.crc.testing:6443/apis/shipwright.io/v1alpha1/namespaces/default/buildruns 200 OK in 11 milliseconds
...
NAME …
```
=> Initialize klog with (go)flags and add these flags to pflag as well

.github/draft_release_notes.sh
converting to PR vs. commit level release notes like we do in the build repo
also pulled in the release note linter we have there
/kind cleanup
- [ n/a] Includes tests if functionality changed/was added
- [n/a ] Includes docs if changes are user-facing
```release-note
NONE
```
=> pull in draft release notes script from build repo

test/e2e/run-follow.bats
Fixes #57
/kind cleanup
- [ /] Includes tests if functionality changed/was added
- [ n/a] Includes docs if changes are user-facing
```release-note
NONE
```
=> adjust shp build run -F e2e so that buildpacks build actually fully completes successfully

pkg/shp/flags/buildrun.go, pkg/shp/flags/buildrun_test.go, pkg/shp/flags/flags.go, test/e2e/output-image-labels-annotations.bats
This adds support to specify labels and annotation for
output image.
There are 2 flags added for the build create command
output-image-label
output-image-annotation
Closes #66 
Also, addresses some left over comments from https://github.com/shipwright-io/cli/pull/68 
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>
```release-note
Adds support to specify labels and annotations on BuildRun objects to be set on output images
```
=> Adds support for img labels and anno. in buildrun create cmd

pkg/shp/cmd/build/run.go, pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/logs.go, pkg/shp/cmd/buildrun/logs_test.go, pkg/shp/cmd/follower/follow.go, pkg/shp/params/params.go, test/e2e/log-follow--follow.bats, test/e2e/log-follow-F.bats
Fixes #80 
/kind feature
A user can now run commands like 
```sh
$ shp buildrun create --buildref-name buildpack-nodejs-build foo ; shp buildrun logs -F foo
```
and tail logs in real time.
- [ /] Includes tests if functionality changed/was added
- [ /] Includes docs if changes are user-facing
```release-note
Added log following / tailing of active buildruns to 'shp buildrun logs' via the '-F' or '--follow' arguments
```
=> add -F / --follow options to shp buildrun logs

.github/draft_release_notes.sh, .github/workflows/release.yml
- Modify release notes script to ensure working tree is clean.
- Remove chmod +x modification on release notes script.
- Use release notes script to draft release notes for goreleaser.
- Convert release workflow from a push action to an on-demand action,
with current and previous release tags as inputs.
Fixes #74 
/kind cleanup
```release-note
NONE
```
=> Generate cleaner release notes

pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/logs_test.go, pkg/shp/cmd/follower/follow.go, pkg/shp/reactor/pod_watcher.go, pkg/shp/reactor/pod_watcher_test.go
This the the PR I promised in https://github.com/shipwright-io/cli/pull/89#issuecomment-1015473951 around the outcome of the discussion @otaviof and I around the admittedly very small timing window around missing pod events when we instantiate the `Follower` after a `BuildRun` is started, which was desired in the case where we utilized the feature to auto generate the `BuildRun` name.
This conceptually is analogous to the "relist" concept you see in k8s controllers to address the possibility of missing watch events.
/kind cleanup
- [ /] Includes tests if functionality changed/was added
- [n/a ] Includes docs if changes are user-facing
- [/ ] Release notes block has been filled in, or marked NONE
See [the …
=> update pod watcher to handle all events occurring before the pod watcher is started

docs/local_source_upload.md
Initial documentation for the local source upload feature (#86).
```release-note
NONE
```
=> Local Source Upload Doc.

.github/draft_release_notes.sh
/kind cleanup
- [ n/a] Includes tests if functionality changed/was added
- [n/a ] Includes docs if changes are user-facing
```release-note
NONE
```
=> fix copy/paste error when grabbing script from build repo

pkg/shp/cmd/buildrun/list.go
Add `AGE` column for `BuildRun` output.
```
NAME                    STATUS               AGE
foo-buildrun-yyyyy      Running              20s
foo-buildrun-xxxxx      Succeeded            19m
```
```release-note
NONE
```
=> Add AGE column for BuildRun output

pkg/shp/cmd/build/create.go
Making `--source-url` optional for `shp build create`.
Fixes #100 
```release-note
Making --source-url optional for `shp build create` subcommand.
```
-->
=> Optional Source URL

.goreleaser.yml, docs/shp_version.md, pkg/shp/cmd/root.go, pkg/shp/cmd/version/version.go
Enable users to see a version on the ship binary. This will be only set when consuming a ship from our releases.
This adds a new main cmd and the necessary changes in the goreleaser to compile the binary with the current version(_based on the latest git tag_).
```release-note
Add version cmd.
```
=> Add version cmd

cmd/shp/main.go, docs/shp.md, docs/shp_build.md, docs/shp_build_create.md, docs/shp_build_delete.md, docs/shp_build_list.md, docs/shp_build_run.md, docs/shp_build_upload.md, docs/shp_buildrun.md, docs/shp_buildrun_cancel.md, docs/shp_buildrun_create.md, docs/shp_buildrun_delete.md, docs/shp_buildrun_list.md, docs/shp_buildrun_logs.md, docs/shp_version.md, pkg/shp/params/params.go, test/e2e/e2e.bats
Hiding the logging flags, and the Kubernetes connection flags as discussed in issue #99. Keeping `kubeconfig`, `namespace`, and `request-timeout` visible.
Fixes #99
```release-note
NONE
```
=> Hide Kubernetes and Logging flags

docs/shp_build_create.md, docs/shp_build_run.md, docs/shp_build_upload.md, docs/shp_buildrun_create.md, pkg/shp/cmd/build/list.go, pkg/shp/flags/build.go, pkg/shp/flags/build_test.go, pkg/shp/flags/buildrun.go, pkg/shp/flags/buildrun_test.go, pkg/shp/flags/flags.go
Adding the flags to set the Build and BuildRun retention. And while I was adding flags, I noticed that for some fields that we now intentionally changed to pointers, the cleanup logic to set those fields to `nil` was missing.
```release-note
You can now set the retention-related fields when creating a Build, or BuildRun
```
=> Add retention flags

pkg/shp/cmd/build/run.go, pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/cancel_test.go, pkg/shp/cmd/buildrun/logs_test.go, pkg/shp/cmd/follower/follow.go, pkg/shp/params/params.go, pkg/shp/reactor/pod_watcher.go, pkg/shp/reactor/pod_watcher_test.go
Fixes #103
/kind cleanup
Hello @otaviof @HeavyWombat @SaschaSchwarze0 
I *finally* got some shipwright cycles this week, and one of my long standing to-do's was to spend quality time on the log following unit test flakes @otaviof reported.
Allow me to explain my process to getting to this point of an alternative PR.
While, as it is clear to see, I initially took a brief pass at reviewing @otaviof 's #104 a month ago, I decided to re-engage here by first making sure I understood first hand what was the crux of the original situation as I remember @otaviof describing in our team meetings, where if I were to attempt to summarize, it was the inherent fragility of k8s fake clients, especially around watches (of course @otaviof please do chime in if my brief summary misses key points).
So …
=> fix flakes in log following related unit tests

pkg/shp/cmd/buildrun/list.go
Fixing #114 by checking if `.Status.StartTime` attribute is `nil`.
```release-note
NONE
```
=> Using ObjectMeta.CreationTimestamp as AGE column

.github/dependabot.yml, .github/workflows/release-notes-linter.yaml
Enabling dependabot alerts based on decision in the https://github.com/shipwright-io/community/issues/78.
Settings are explained in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
We explicitely add the release note none label and skip the Release Note Linter action because it is not possible to configure the pull request to contain our required section.
Fixes #113
```release-note
NONE
```
=> Enable dependabot updates

OWNERS
- Add @coreydaley as reviewer and approver
- Move @alicerum, @gabemontero, and @sbose78 to emeritus_approvers
Signed-off-by: Adam Kaplan <adam.kaplan@redhat.com>
/kind cleanup
```release-note
NONE
```
=> Add coreydaley to OWNERS

Makefile, hack/install-shipwright.sh, hack/install-tekton.sh, pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/logs_test.go, pkg/shp/cmd/follower/follow.go, test/e2e/log-follow--follow.bats, test/e2e/log-follow-F.bats, test/e2e/run-follow.bats, test/mock/fake_clientset.go
So far, whenever a BuildRun failed, we dumped the whole Pod object. This was imo not usable. One was just about to see the cause of the failure at the end of the logs when it dumps ten meters of mostly unuseful JSON.
Instead, when there is a failed container information in the BuildRun status, then I am only printing its container status. On top I am printing the failure reason and message if available.
e2e is included.
I also updated the test suite to use v0.10 of Shipwright and the recent Tekton version.
This also removes the use of `io/ioutil`, fixes #133 
```release-note
When following the logs of a BuildRun that is failing, you now get improved details at the end.
```
=> Improve log output when following failing BuildRun

OWNERS
Removing @gabemontero and @sbose78 also from reviewers to prevent them to be asked for a review like in https://github.com/shipwright-io/cli/pull/137.
```release-note
NONE
```
=> Remove emeritus approvers from reviewers

.github/workflows/e2e.yaml, .github/workflows/release.yml, .github/workflows/unit.yaml, .github/workflows/verify.yaml, hack/install-kind.sh
Similar changes as in https://github.com/shipwright-io/build/pull/1085. Updating the actions. Also updating the Kubernetes version that we test with to 1.23.10.
```release-note
NONE
```
=> Update GitHub actions

.github/workflows/verify.yaml, go.mod, go.sum, vendor/github.com/onsi/gomega/.gitignore, vendor/github.com/onsi/gomega/CHANGELOG.md, vendor/github.com/onsi/gomega/format/format.go, vendor/github.com/onsi/gomega/gomega_dsl.go, vendor/github.com/onsi/gomega/internal/assertion.go, vendor/github.com/onsi/gomega/internal/async_assertion.go, vendor/github.com/onsi/gomega/internal/duration_bundle.go, vendor/github.com/onsi/gomega/internal/gomega.go, vendor/github.com/onsi/gomega/internal/polling_signal_error.go, vendor/github.com/onsi/gomega/types/types.go, vendor/modules.txt
Trying something. golangci-lint in https://github.com/shipwright-io/cli/pull/146/files complains about the gomaga usage in build_test.go. After some try-and-error, that seems to happen because we have no setup-go step in the GitHub action.
```release-note
NONE
```
=> Add setup-go to verify

pkg/shp/cmd/follower/follow.go
Just stumbled over a missing line break while running a build with log following:
```
BuildRun "my-buildrun-fx86c" log following has not observed any pod events yet.
BuildRun 'my-buildrun-fx86c' has not been marked as started yet.
Pod "my-buildrun-fx86c-qlgqs-pod" is in state "Pending"...
Pod "my-buildrun-fx86c-qlgqs-pod" is in state "Pending"...
Pod "my-buildrun-fx86c-qlgqs-pod" is in state "Pending"...
Pod "my-buildrun-fx86c-qlgqs-pod" is in state "Pending"...
Pod "my-buildrun-fx86c-qlgqs-pod" is in state "Pending"...
Pod "my-buildrun-fx86c-qlgqs-pod" is in state "Pending"...
Pod "my-buildrun-fx86c-qlgqs-pod" in "Running" state, starting up log tail[prepare] 2022/11/02 19:58:47 Entrypoint initialization
[source-default] 2022/11/02 19:58:54 Info: ssh (/usr/bin/ssh): OpenSSH_8.0p1, …
```
=> Add missing line breaks

.github/workflows/release.yml
The latest version removed the replacements feature. Therefore pinning to v1.18.2. Same as https://github.com/google/go-containerregistry/pull/1763/files
```release-note
NONE
```
=> Pin goreleaser version

pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/logs_test.go, pkg/shp/cmd/runner/runner_test.go, pkg/shp/cmd/version/version.go, pkg/shp/flags/build_test.go, pkg/shp/flags/buildrun_test.go, pkg/shp/params/params_test.go, pkg/shp/reactor/pod_watcher_test.go
This fixes the new golangci-lint findings that currently block pull requests.
```release-note
NONE
```
=> Fix unused variables

.github/dependabot.yml
Dependabot will bump actions version automatically.
```release-note
NONE
```
=> Include GitHub Actions version in Dependabot setup

.github/workflows/release.yml
Update the release workflow to accept a git reference as a parameter. This will be used to check out the appropriate release branch when generating artifacts and release notes. The workflow then creates a tag for the release, which is required by GoReleaser in a subsequent step.
The action was also updated to use the (new?) inputs context, instead of relying on the inputs key existing in the github.events payload.
Part of #238 
/kind cleanup
```release-note
NONE
```
=> SHIP-0038: Add Git Ref to Release Workflow

.github/actions/setup/action.yaml, .github/workflows/release.yml, go.mod
- Updated Go version to 1.21
- Fixes #221 
```release-note
NONE
```
=> updated go version to 1.21

pkg/shp/bundle/bundle.go, pkg/shp/cmd/build/upload.go, pkg/shp/streamer/streamer.go, pkg/shp/streamer/streamer_test.go, pkg/shp/streamer/tar.go, pkg/shp/streamer/util.go
Remove tar size calculation and replace it with counting a run through the create.
Add check to verify that changing the max is required.
Fixes #269
```release-note
Fixed local source code progress bar output that displays the actual size of the data being transferred.
```
=> Fix incorrect tar size calculation

Makefile
Remove the verbose flag from Go build command, since this doesn't produce helpful output in almost all cases and is just slowing down the build slightly.
```release-note
NONE
```
=> Remove verbose flag for build

pkg/shp/cmd/follower/follow.go
Finding: printf: non-constant format string in call to fmt.Errorf (govet)
Use `errors.New` instead of `fmt.Errorf` without formatting.
```release-note
NONE
```
=> Fix `golangci-lint` findings

docs/shp_build_create.md, docs/shp_build_run.md, docs/shp_build_upload.md, docs/shp_buildrun_create.md, pkg/shp/flags/build.go, pkg/shp/flags/buildrun.go, pkg/shp/flags/flags.go, pkg/shp/flags/param_value.go, pkg/shp/flags/param_value_test.go
This commit enables the option to pass custom/required parameters via CLI while creating the build or buildRun.
Fixes #224 
```release-note
Shipwright CLI extends support to set the parameters using "--param-value" flag while creating build/buildRun.
```
=> Adds flag to add paramValues

.github/actions/setup/action.yaml, .github/workflows/release.yml, go.mod
Use latest Go version `1.22` for any Go related GitHub Action.
```release-note
NONE
```
=> Use Go `1.22` in GitHub Actions

.github/workflows/build-check.yaml, .goreleaser.yml
Add version to GoReleaser configuration.
Fix deprecated `name_template` usage.
Add GitHub Action to regularly check the configuration and build.
Fixes #288
```release-note
NONE
```
=> Fix GoReleaser config warnings/issues

.golangci.yml, hack/verify-docs.sh, pkg/shp/cmd/buildrun/logs.go, pkg/shp/cmd/follower/follow.go, pkg/shp/reactor/pod_watcher.go, pkg/shp/streamer/util.go, test/e2e/envvars.bats
While working on https://github.com/shipwright-io/cli/pull/291, I realized that my [linter](https://github.com/go-critic/go-critic) returned some minor findings in this repository.
Fix minor TYPO in `hack/verify-docs.sh`.
Resolve `gocritic` findings.
Remove trailing whitespaces.
```release-note
NONE
```
=> Fix `gocritic` findings

.github/actions/setup/action.yaml, .github/workflows/release.yml, go.mod
Bumps the go version in GHA to v1.23
-->
```release-note
NONE
```
=> Bump Go version to `1.23`

docs/shp_build_create.md, docs/shp_build_run.md, docs/shp_build_upload.md, docs/shp_buildrun_create.md, pkg/shp/flags/build.go, pkg/shp/flags/build_test.go, pkg/shp/flags/buildrun.go, pkg/shp/flags/buildrun_test.go, pkg/shp/flags/flags.go, test/e2e/node-selector.bats
Fixes #260 
Add CLI flag `--node` to set `.spec.nodeSelector` to a `Build` or `BuildRun` 
❗ **IMPORTANT:** depends on [PR 304](https://github.com/shipwright-io/cli/pull/304)
PR's codebase is tracking [PR 304](https://github.com/shipwright-io/cli/pull/304) by @karanibm6 as `.spec.nodeSelector` is only defined on `builds.shipwright.io/v1beta1` as a consequence of the current `main` branch for CLI relying on `builds.shipwright.io/v1alpha1` (see [PR 1683](https://github.com/shipwright-io/build/pull/1683))
```release-note
Add flag --node-selector to set the `.spec.nodeSelector` for `build` and `buildrun` on …
```
=> Add `--node-selector` Flag for `shp build/buildrun` Commands

docs/shp_build_create.md, docs/shp_build_run.md, docs/shp_build_upload.md, docs/shp_buildrun_create.md, pkg/shp/flags/build.go, pkg/shp/flags/build_test.go, pkg/shp/flags/buildrun.go, pkg/shp/flags/buildrun_test.go, pkg/shp/flags/flags.go, test/e2e/node-selector.bats
Fixes #261 
Add CLI flag `--scheduler-name` to set `.spec.schedulerName` to a `Build` or `BuildRun` 
❗ **IMPORTANT:** depends on my other [PR 309](https://github.com/shipwright-io/cli/pull/309) as `v1beta1` is required (and inherently to [PR 304](https://github.com/shipwright-io/cli/pull/304))
```release-note
Add flag --scheduler-name to set the `.spec.schedulerName` for `build` and `buildrun` on create and run
```
=> Ship 0039/261 - add --scheduler-name flag

.golangci.yml, pkg/shp/cmd/build/run_test.go, pkg/shp/cmd/buildrun/cancel_test.go, pkg/shp/cmd/buildrun/logs_test.go, pkg/shp/cmd/follower/follow.go, pkg/shp/flags/build_test.go, pkg/shp/flags/flags.go, pkg/shp/flags/param_value.go, pkg/shp/params/params.go, pkg/shp/params/params_test.go, pkg/shp/reactor/pod_watcher_test.go, pkg/shp/streamer/streamer_test.go, pkg/shp/streamer/tar_test.go, pkg/shp/streamer/target.go, pkg/shp/tail/tail_test.go, test/mock/fake_clientset.go
- Refactor command-line flag variables
- Add comments to exported functions
- Remove unused pointer-receiver function
- Unify Gomega import and usage
- Simplify code as suggested by linter
- Disable package comment linter
- Add error check in unit-test cases
```release-note
NONE
```
=> Address `golangci-lint` findings

go.mod, go.sum, vendor/modules.txt
Bump shipwright build dep to v0.16.0
Update go deps
```release-note
Bump Shipwright Build to v0.16.0
```
=> Bump shipwright build dep to v0.16.0

pkg/shp/cmd/build/upload.go, pkg/shp/streamer/streamer.go, pkg/shp/streamer/streamer_test.go
- Data stream was only being initialized when the source is not OCI artifact. Hence, in cases where the source itself is not specified in the Build object, the struct was left uninitialized
- Explicitly set UID and GID to 0 in "tar" header while writing archive, to prevent permission issue with local file having different UID and GID
Fixes #332 
Fixes #338 
```release-note
Fixes bugs with builds from local source code
```
=> Fix local source build

pkg/shp/cmd/buildrun/list.go
- Check if BuildSpec exists in Status of BuildRun, since it an optional field in the API
- Try to get SourceOrigin from BuildRunSpec if it doesn't exist in BuildRun status.
Fixes #339 
```release-note
Fixes "buildrun list" command for BuildRuns with invalid BuildSpec.
```
=> Fix buildrun list command

.github/workflows/release.yml
Use the shared Setup action to install go and ko.
/kind bug
```release-note
Fix release action to install common base version of compile tools.
```
=> [release-v0.17] fix: Run Shared Setup for Release
